### ISSUE TITLE
GUI improve for core wallet - cold staking (Video Demo)

### ISSUE THREAD

**Issue by kakax114** [navcoin/navcoin-core#384]
![suggestion-receive-screen-_cold-staking_](https://user-images.githubusercontent.com/29662491/50196487-3203a700-03a8-11e9-9c37-f496ac6b9652.gif)

**Comment by mxaddict** [comment]
@kakax114 , can you explain why the UI demo that you created shows creating many cold stake addresses based on one spend address?

That does not seem like a useful feature.

Maybe you can shed some light on why you want to change the UI to be more like this?

**Comment by kakax114** [comment]
@mxaddict Hi, thanks for the feedback, it only generates a single address, maybe the "show all addresses" confuses you which makes sense, maybe better change it to "list old addresses" then

**Comment by mxaddict** [comment]
What I'm asking is why do you need to make many cold staking addresses?

1. The more cold staking addresses you have, the less NAV each of them would have (Longer time to stake for each address)
2. Seems that the UI is showing the ability to create COLD addresses in the UI based on the same spending address (I don't see the use of this, If you have the same spend address, then you might as well use the same stake address since the stake address is technically safe to loose)
3. The list feature is actually nice, It's much better than the current list that is shown in a dialog/popup

**Comment by mxaddict** [comment]
I think the UI that you have makes sense, except for the checkbox that allows you to create cold staking addresses with a single spend address (I don't see a use for it, please give me a scenario so that I can understand)

But the the rest of the UI looks nice, Maybe even just have the list of addresses always showned? No need to click the show old addresses button, (That click is just an extra step that can be removed)

Let me know what you think.

**Comment by kakax114** [comment]
Fair enough and great to have your input. Yes, your suggestion is correct, my design is based on the fact that wallet allows you to generate a lot of new addresses, so should behave the same in even its cold staking address, and the checkbox that allows you to create cold staking addresses with a single spend address is because the address can be randomly generated just like you click through the "generate new", so i was intended to save a step. But if most users only needs 1 staking address for staking their coins then there's no need to have it, you can just have the advanced view as default!

**Comment by mxaddict** [comment]
@aguycalled  @kakax114 I think the current UI on 5.x and even 6.x are very different from the UI in this issue now, I think we should close this and maybe come up with a different concept that's more applicable with the current UI of the wallet.
