### ISSUE TITLE
Crash when new version alert pops up

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#476]
User reported crash of his wallet when the wallet shows the popup alerting a new version is available (https://github.com/navcoin/navcoin-core/blob/master/src/main.cpp#L3677).

It coincides with a steep fall in the difficulty around block 3111970 (https://chainz.cryptoid.info/nav/#@diff), making me think around that height >40% of the blocks were mined with 4.6.0, triggering the alert and causing all the nodes running an old version to crash.

I was not able to reproduce the issue by:
- Connecting a modified 4.6.0 to mainnet and modifying:
`int32_t nExpectedVersion = CLIENT_VERSION-10000;`
and
`if (nUpgraded > 10/2.5)`.
- Connecting a 4.5.2 client to mainnet.
- Using devnet with 2 local nodes with 4.6.0 and 4.5.2 and forcing the alert to show.

In all the cases I tested under OSX and the alert showed successfully without crash.

There's evidence the issue is real (or there might be other reason for the crashes) so it's worth to investigate.

**Comment by mxaddict** [comment]
I could not replicate this with my machines, I installed older versions and got the pop up / warning for did not crash.

**Comment by lokacesh** [comment]
I was running v4.5.2 when I received an alert of a new version but it did not crash. I am on Win 10 64-bit.

**Comment by mxaddict** [comment]
I think I was able to get a windows wallet to crash with the pop up.

Seems it happened when the popup was already open, then another 1000 blocks came in with new version bit, and the pop up tried to open again.

I'll see if I can replicate this again on test/devnet and upload some more info

@aguycalled  @craigmacgregor

**Comment by aguycalled** [comment]
were you able to replicate this? @mxaddict

**Comment by mxaddict** [comment]
Yes on windows, but I'm not sure if it was the wallet if it was because i was playing games when the pop up came.

It wasn't really a crash, it was more like i could not get the OS to focus on the wallet so I had to kill it via task manager. 

Basically the pop up came up, then I noticed that the wallet was not hung, so I left it open. 

Then i was playing Rainbow Six Siege. Then the pop up opened agian. But I could not get focus on the wallet, alt tab and clicking on wallet icon did not work. So I just killed it via task manager.

**Comment by mxaddict** [comment]
Was anyone else able to replicate this?

**Comment by mxaddict** [comment]
Is anyone still experiencing this? I could not replicate.

**Comment by aguycalled** [comment]
we disabled the popup

**Comment by mxaddict** [comment]
I guess we can close this now.
