### ISSUE TITLE
Spelling/graphic error of GUI on cfund page

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-core#478]
![image](https://user-images.githubusercontent.com/38635377/57494558-76c4a780-728f-11e9-97be-d5f14ef61699.png)

**Comment by hdnsimpson** [comment]
I have noticed this too after the 4.6.0 release, but haven't had any time to make any changes

**Comment by lokacesh** [comment]
![NAV Core GUI Issue](https://user-images.githubusercontent.com/50619183/57689077-7e53ca00-765c-11e9-9c0b-eb563035147c.png)

Few more quirks:
1.) There is some scaling issue with Windows OS. Currently my laptop is set at recommended 125% scaling and NAV Core's Fonts are not scaling properly.
2.) We have "1ndia and 0ndia" instead of "India".
3.) The lines underlined in "red" does not look good and can be replaced with "dots" when there is less space or can use smaller fonts.

**Comment by sherlockcoin** [comment]
I think this was fixed in 4.6.0? @aguycalled

**Comment by mxaddict** [comment]
I think this is No longer applicable as of the new #530 PR
