### ISSUE TITLE
NULL vs nullptr

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#508]
I've noticed a lot of code that uses NULL and remembered that we use c++11 during compile

@aguycalled  @proletesseract Maybe we should replace all NULL with nullptr? Or is there a good reason to keep using NULL?

**Comment by mxaddict** [comment]
Hmmmm, but then again, we initialize alot of variables with (0), I'm not sure if we need to change those to use nullptr

**Comment by aguycalled** [comment]
i'd say the change is safe as long as we are sure we only move pointers to nullptr

**Comment by mxaddict** [comment]
Hmmmm, I just skimmed over the NULL instances, but as far as I saw, there were not any dangerous instances, I guess we can have this change on the back burner for now since it could potentially add bugs.

**Comment by mxaddict** [comment]
What do you think @proletesseract?

**Comment by alexeyneu** [comment]
it will be better to refractor code to 2003  first.   this stuff has 8088(?) era 8-bit syntax.  
https://github.com/navcoin/navcoin-core/blob/4fb8043f068fae1814ff76049a45f237b4df6f8e/src/init.cpp#L1034  
as you  know that's why it has 3 args where `malloc` has two  
in c++ '2003 it will be like that:  
https://github.com/alexeyneu/libbase58/blob/5944699a76bb36c73fc7889e26f60e78b4952858/base58_c.cpp#L36  
And with all this understanding you then could hunting for `NULL`s .
