### ISSUE TITLE
undefined symbol: SSLeay

### ISSUE THREAD

**Issue by ITwrx** [NAVCoin/navcoin-core#68]
trying to run navcoin-qt on arch linux. i get: 
`./navcoin-qt: symbol lookup error: ./navcoin-qt: undefined symbol: SSLeay`
thanks

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T15:19:26+13:00","ped":"2017-11-22T17:59:26+13:00"})

**Comment by aguycalled** [comment]
Is arch linux your distribution or architecture?

alex

**Comment by ITwrx** [comment]
distro

**Comment by aguycalled** [comment]
I’d suggest you to try the x86_64 binary.

**Comment by ITwrx** [comment]
i am. navcoin-4.0.3-x86_64-linux-gnu
thanks

**Comment by aguycalled** [comment]
Are all the dependencies as documented in https://github.com/NAVCoin/navcoin-core/blob/master/doc/build-unix.md setup?

**Comment by ITwrx** [comment]
are these debian package names or something?

**Comment by ITwrx** [comment]
so, if i'm understanding this correctly, navcoin won't work on arch (without replacing my berkely databse version with 4.8 which may not be compat with the rest of my system) because navcoin uses a very old berkely database for compat with debian/ubuntu. Is this the situation?

**Comment by aguycalled** [comment]
Nav binaries come with the right berkeley-db version.

I'd say the message you are seeing means a) you are using a binary with the wrong architecture or b) there's a problem with openssl in your system.

Sadly I don't have an ArchLinux where I could test it deeper.

**Comment by ITwrx** [comment]
i'm using the qt binary that was in the x86_64 tarball with a 64 bit system. 
i have openssl 1.1.0.e-1 and openssl-1.0 1.0.2.k-3 installed. the 1.1 version is arch default and the 1.0 version is an older version required as dependency of qt5-base. Maybe there is an incompatability between the wallet and one or both of these openssl packages?

**Comment by YanArnd** [comment]
Same problem with same navcoin-qt binary (4.0.3-x86_64) here on Fedora 26 64bit (having OpenSSL 1.1.0f and a "compat-openssl10-1.0.2j" package installed).
Maybe it would help to include the OpenSSL stuff in the binary. The bleeding-edge distros' OpenSSL versions seem to be incompatible with the current NavCoin codebase.

**Comment by cercos** [comment]
Has this issue been fixed?  I am trying to run the NAV coin wallet on Arch and getting the undefined symbol: SSLeay error.  Have asked on forum, slack, and reddit page and feel as though it gets ignored, never even get a response.

**Comment by miloops** [comment]
I'm getting the same error on Arch. Looks like openssl issue.

If I try to compile from source I get this on `make check`:

```
➜  navcoin-core git:(master) ✗ make check
Making check in src
make[1]: Entering directory '/home/miloops/media/blockchain/navcoin-core/src'
make[2]: Entering directory '/home/miloops/media/blockchain/navcoin-core/src'
make[3]: Entering directory '/home/miloops/media/blockchain/navcoin-core/src/secp256k1'
make[3]: Leaving directory '/home/miloops/media/blockchain/navcoin-core/src/secp256k1'
  CXX      libnavcoin_server_a-blockencodings.o
In file included from wallet/walletdb.h:12:0,
                 from main.h:24,
                 from blockencodings.cpp:13:
./key.h:238:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./key.h:16,
                 from wallet/walletdb.h:12,
                 from main.h:24,
                 from blockencodings.cpp:13:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from wallet/walletdb.h:12:0,
                 from main.h:24,
                 from blockencodings.cpp:13:
```

**Comment by scordeiro** [comment]
@aguycalled I'm having the same issue as @miloops in Arch, either executing QT wallet's binary or trying to compile.

I found this code fix on BitShares for code that seems similar to the one that's throwing the error(s) under NAV's code, it might help get the compatibility between old and newer OpenSSL libs fixed: https://github.com/bitshares/bitshares-fc/commit/fee06a4

**Comment by scordeiro** [comment]
@aguycalled I'm having the same issue as @miloops in Arch, either executing QT wallet's binary or trying to compile.

I a code fix on BitShares for code that seems similar to the one that's throwing the error(s) under NAV's code, unfortunately it was reverted because "_Max compatible Boost version is not compatible with OpenSSL 1.1.0_".

Still, I didn't try it out so it might or might not help getting the compatibility between old and newer OpenSSL libs fixed:

Original fix commit: https://github.com/bitshares/bitshares-fc/commit/fee06a4
Reversal fix commit: https://github.com/bitshares/bitshares-fc/commit/a30647d32e0580217e4bfcb7ccf5493766fcdc0c

OpenSSL 1.1.0 broke some things from 1.0.2 so this might be one of it.

I hope this can help in any way.

**Comment by scordeiro** [comment]
@aguycalled @miloops, I was able to recompile everything with OpenSSL 1.0 using the following _configure_ command AND changing the _src/qt/navcoingui.h_ header file to eliminate a couple of repeated declarations, namely, _void toggleStacking();_ and _QAction * toggleStackingAction();_ that were throwing the error below.

Configure command used after _./autogen.sh_ and before the make command:

`LDFLAGS=" -L/usr/lib/openssl-1.0 -lssl -L/usr/lib ${LDFLAGS}" CPPFLAGS="-I/usr/include/openssl-1.0 -fPIC -O3 ${CPPFLAGS}"  CXXFLAGS="-I/usr/include/openssl-1.0 -fPIC -O3 ${CXXFLAGS}" PKG_CONFIG_PATH="/usr/lib/openssl-1.0/pkgconfig ${PKG_CONFIG_PATH}" CFLAGS="-fPIC -O3${CFLAGS}" ./configure --with-incompatible-bdb --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib`

Declarations error in _navcoingui.h_ header file:

> `In file included from qt/navcoin.cpp:9:0:
> qt/navcoingui.h:148:14: error: redeclaration of ‘QAction* NavCoinGUI::toggleStakingAction’
>      QAction *toggleStakingAction;
>               ^~~~~~~~~~~~~~~~~~~
> qt/navcoingui.h:128:14: note: previous declaration ‘QAction* NavCoinGUI::toggleStakingAction’
>      QAction *toggleStakingAction;
>               ^~~~~~~~~~~~~~~~~~~
> In file included from qt/navcoin.cpp:9:0:
> qt/navcoingui.h:248:10: error: ‘void NavCoinGUI::toggleStaking()’ cannot be overloaded
>      void toggleStaking();
>           ^~~~~~~~~~~~~
> qt/navcoingui.h:236:10: error: with ‘void NavCoinGUI::toggleStaking()’
>      void toggleStaking();
> ` 

Seems to have worked, _navcoin-qt_ successfuly generated, I've opened the wallet and I've inputed the base NAVTech server and it's syncing

Regarding the OpenSSL 1.1.0 version compatibility, I found an issue under bitcoin that has several references to other issues that were referenced in order to solve this compatibility:

* https://github.com/bitcoin/bitcoin/issues/7086

I hope it's useful.

**Comment by aguycalled** [comment]
I'll keep investigating on this, right now we use openssl 1.0.1 when building the binaries

**Comment by ata** [comment]
I download wallet for linux x86_amd64, when I ran it, this is what I got
```
./navcoin/bin/navcoin-qt: symbol lookup error: ./navcoin/bin/navcoin-qt: undefined symbol: SSLv3_client_method
```

From What I see, seem like navcoin wallet can't run with openssl1.1
My computer use GNU/Linux Debian 9.1 (current stable). There no way to install openssl1.0 simultaneous with openssl1.1
In my opinion, if Debian as the mother of many disto can't run navcoin wallet, I'm pretty sure that navcoin wallet can't run in many distro as well.

**Comment by aguycalled** [comment]
possible fix: https://github.com/peercoin/peercoin/commit/5b09830e5de0f5105534e69dbf4acffb3255869b

**Comment by aguycalled** [comment]
Solved, pending pr
