### ISSUE TITLE
Unable to build from master on Ubuntu 18.04

### ISSUE THREAD

**Issue by skironDotNet** [navcoin/navcoin-core#940]
used your script to build navcoin on Ubuntu 18.04
All runs ok... well had to add 1 lib by hand https://github.com/navcoin/navcoin-dev-tools/issues/6

#install unbound ok
autogen, configure all ok, but fails on `make`
```
  cd navcoin-core
  git checkout master
  cd depends
  make
  cd ..
  ./autogen.sh
  ./configure --enable-debug --enable-tests --prefix=`pwd`/depends/`uname -m`-pc-linux-gnu 
  make -j$(nproc)
```

![image](https://user-images.githubusercontent.com/2981715/157319944-eae6f071-0a60-460c-8b20-64d763b1fa8d.png)

Any idea? Should I build from release tag? or something is broken? Can your test your script with fresh Ubuntu VM? https://github.com/navcoin/navcoin-dev-tools/blob/master/ubuntu-18.04-navcoin-core-dev-setup.sh

**Comment by skironDotNet** [comment]
Same error when build from Tag 7.0.1 which is your release code. How to build?

**Comment by aguycalled** [comment]
https://doc.nav.community/get.html

**Comment by mxaddict** [comment]
I think you need to run this: `sudo apt -y install build-essential libtool autotools-dev automake pkg-config git cmake libattr1-dev python3-dev` Sent from Mail for Windows From: Pawel CiochSent: Wednesday, 9 March 2022 4:34 amTo: navcoin/navcoin-coreCc: SubscribedSubject: [navcoin/navcoin-core] Unable to build from master on Ubuntu 18.04 (Issue #940) used your script to build navcoin on Ubuntu 18.04All runs ok... well had to add 1 lib by hand navcoin/navcoin-dev-tools#6#install unbound okautogen, configure all ok, but fails on make  cd navcoin-core  git checkout master  cd depends  make  cd ..  ./autogen.sh  ./configure --enable-debug --enable-tests --prefix=`pwd`/depends/`uname -m`-pc-linux-gnu   make -j$(nproc)Any idea? Should I build from release tag? or something is broken? Can your test your script with fresh Ubuntu VM? https://github.com/navcoin/navcoin-dev-tools/blob/master/ubuntu-18.04-navcoin-core-dev-setup.sh—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by skironDotNet** [comment]
@mxaddict I have all those libs installed, it's not about that. 

I'll ping you back once I test the guide from @aguycalled

**Comment by skironDotNet** [comment]
@aguycalled your guide helped. The key part for Ubuntu 18 is
![image](https://user-images.githubusercontent.com/2981715/157520732-11ddc687-b541-4591-bc0a-d4fd31832eaf.png)

This note could be presented as warning, because without it can't really build.
Also would be good idea to update in git documentation with that. And maybe the script https://github.com/navcoin/navcoin-dev-tools/blob/master/ubuntu-18.04-navcoin-core-dev-setup.sh

Should update CMAKE automatically on 18?

**Comment by aguycalled** [comment]
would you like to take this task and update [https://github.com/navcoin/navcoin-dev-tools](https://github.com/navcoin/navcoin-dev-tools/blob/master/ubuntu-18.04-navcoin-core-dev-setup.sh)? @mxaddict

**Comment by skironDotNet** [comment]
Seems like I spoke too early... So it was building and building but ended same way as start with older CMAKE

![image](https://user-images.githubusercontent.com/2981715/157532366-d7a02d5d-de3a-44c8-bbfa-1136f28a80e2.png)

Are you sure there are no errors in Makefile? but then it makes no sense because you wouldn't be able to make either.
I could try Ubuntu 20...

**Comment by aguycalled** [comment]
I see no error in the screenshot. you should have the binaries in `src/navcoin-cli` and `src/qt/navcoin-qt`

**Comment by mxaddict** [comment]
> 

This looks like the build worked fine.

try running the gui wallet with `./src/qt/navcoin-qt -devnet`

**Comment by mxaddict** [comment]
@aguycalled  @skironDotNet  could you test this PR and see if it's working as I expected: https://github.com/navcoin/navcoin-dev-tools/pull/7

**Comment by mxaddict** [comment]
This PR changes the build script to work with both 18.04 and 20.04

**Comment by skironDotNet** [comment]
Ok, sorry, I thought this is an error https://github.com/navcoin/navcoin-core/issues/940#issuecomment-1063354190 didn't check the `src/qt` folder. It got build.

Thank you for your support, and sorry for unnecessary confusion.

**Comment by skironDotNet** [comment]
@mxaddict regarding https://github.com/navcoin/navcoin-dev-tools/pull/7 I don't enable debug and disable tests to make build faster for me. Tests are good for you to test after new changes I'm assuming

My core part of build script is this (after having all needed libs installed and pulled git repo)
```
cd depends
sudo make -j$(nproc)
cd ..
sudo ./autogen.sh
sudo ./configure --disable-tests --prefix=`pwd`/depends/`uname -m`-pc-linux-gnu 
sudo make -j$(nproc)
```

So needed updated CMAKE version on 18.04 as I mentioned here https://github.com/navcoin/navcoin-core/issues/940#issuecomment-1063293977
**and needed exec all core commands as sudo**

Also to minimize binary size at the end I call 
```
strip navcoind
strip navcoin-qt
```
and so on

**Comment by mxaddict** [comment]
I've updated the script in dev-tools repo to use newer cmake.

If you have a fresh ubuntu 18.04 vm, maybe give it a shot.

**Comment by stenolog** [comment]
@aguycalled, looks closable

**Comment by skironDotNet** [comment]
Nobody uses 18.04 anymore, just close it

**Comment by stenolog** [comment]
@skironDotNet , you (as the author) should be able to close the issue

**Comment by skironDotNet** [comment]
somehow there were no option to close from github mobile app
